photoneo_camera:
  
  connection:
    # device_id: 'PhotoneoTL_DEV_2019-06-011-LC3'
    device_id: PhotoneoTL_DEV_InstalledExamples-basic-example

  output:
    directory: "tmp/captured_images"
    image_format: "png"
    point_cloud_format: "ply"
    save_options: '{"Mesh": true, "DepthMap": true, "PointCloud": true, "NormalMap": true}'
  
  capture:
    PhotoneoTriggerMode: 'Software'
    AmbientLightSuppression: true
    CodingStrategy: 'Interreflections'

  point_cloud_settings:
    SendTexture: true
    SendPointCloud: true
    SendNormalMap: true
    SendDepthMap: true
    SendConfidenceMap: true

  processing:
    InterreflectionsFiltering: true
    InterreflectionFilterStrength: 0.5
    MaxInaccuracy: 2.0

  coordinate_space:
    CoordinateSpace: 'RobotSpace'
    TransformationSpaceSelector: 'Robot'